import './global.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import React from 'react';
import Layout from '../components/layout';
export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  "use client"
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Layout>
            {children}
          </Layout>
        </UserProvider>
      </body>
    </html>
  );
}
