import './global.css';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <UserProvider>
        <Theme>
          <Header/>
          {children}
          <Footer/>
        </Theme>
      </UserProvider>
      </body>
    </html>
  );
}
